server:
  port: 9091


spring:
  thymeleaf:
    cache=false:
  profiles:
    active: local

  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: "jdbc:log4jdbc:mariadb://192.168.0.105:3306/DOCKER?allowPublicKeyRetrieval=true&useSSL=false"
    username: root
    password: oacxpwd@1
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 50
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      pool-name: pool-docker-manager
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  type-aliases-package: com.docker.dockermanager.entity
  mapper-locations: /mapper/*.xml
  configuration.map-underscore-to-camel-case: true

thymeleaf.prefix: classpath:/templates

logging:
  level:
    "[root]": DEBUG
    "[com.zaxxer.hikari]": INFO
    "[com.zaxxer.hikari.HikariConfig]": DEBUG
    "[org.mybatis.spring]": INFO
    "[org.springframework.jdbc.support]": INFO




